from __future__ import annotations

import shutil
import subprocess
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import BinaryIO

import pytest

from doctovid.config import Config, load
from doctovid.jobs import Job, Mode, Request
from doctovid.media import MediaInfo
from doctovid.progress import ProgressCallback
from doctovid.store import Store
from doctovid.transport import Keyboard

needs_ffmpeg = pytest.mark.skipif(
    shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None,
    reason="ffmpeg is not installed",
)

MakeClip = Callable[..., Path]


@pytest.fixture
def make_clip(tmp_path: Path) -> MakeClip:
    """A two-second test video, generated by ffmpeg with the codecs asked for."""

    def make(name: str, video: str = "mpeg4", audio: str | None = "aac") -> Path:
        path = tmp_path / "clips" / name
        path.parent.mkdir(exist_ok=True)
        command = ["ffmpeg", "-nostdin", "-y", "-loglevel", "error"]
        command += ["-f", "lavfi", "-i", "testsrc=duration=2:size=320x240:rate=15"]
        if audio is not None:
            command += ["-f", "lavfi", "-i", "sine=duration=2", "-c:a", audio]
        command += ["-c:v", video, "-shortest", str(path)]
        subprocess.run(command, check=True)
        return path

    return make


@pytest.fixture
def config(tmp_path: Path) -> Config:
    return load(
        {
            "API_ID": "1",
            "API_HASH": "hash",
            "BOT_TOKEN": "token",
            "ADMIN_IDS": "7",
            "CACHE_CHANNEL_ID": "-1001234",
            "DATA_DIR": str(tmp_path / "data"),
        }
    )


@pytest.fixture
def store(tmp_path: Path) -> Store:
    return Store(tmp_path / "test.db")


def make_request(file_name: str = "clip.mkv", **overrides: object) -> Request:
    values: dict[str, object] = {
        "id": 1,
        "user_id": 42,
        "message_id": 100,
        "document_id": 555,
        "file_name": file_name,
        "size": 1000,
        "mime_type": None,
        "is_video": True,
        "expires_at": 1e12,
        "menu_message_id": 101,
    }
    values.update(overrides)
    return Request(**values)  # type: ignore[arg-type]


def make_job(request: Request | None = None, mode: Mode = Mode.VIDEO, job_id: int = 1) -> Job:
    return Job(id=job_id, request=request or make_request(), mode=mode)


@dataclass
class Upload:
    chat_id: int
    name: str
    video: MediaInfo | None
    thumbnail: bytes | None
    content: bytes


@dataclass
class FakeTransport:
    """Telegram as the runner sees it. Files the user sent live in `sent_files`."""

    sent_files: dict[int, Path] = field(default_factory=dict)
    uploads: list[Upload] = field(default_factory=list)
    copies: list[tuple[int, int, int]] = field(default_factory=list)
    edits: list[str] = field(default_factory=list)
    deleted: list[int] = field(default_factory=list)
    gone: set[int] = field(default_factory=set)
    next_id: int = 1000

    async def download(
        self, chat_id: int, message_id: int, dest: str, progress: ProgressCallback
    ) -> bool:
        source = self.sent_files.get(message_id)
        if source is None:
            return False
        shutil.copyfile(source, dest)
        size = source.stat().st_size
        await progress(size, size)
        return True

    async def upload(
        self,
        chat_id: int,
        file: BinaryIO,
        *,
        size: int,
        name: str,
        video: MediaInfo | None,
        thumbnail: bytes | None,
        reply_to: int | None,
        progress: ProgressCallback,
    ) -> int:
        content = file.read()
        assert len(content) == size
        self.uploads.append(Upload(chat_id, name, video, thumbnail, content))
        self.next_id += 1
        return self.next_id

    async def copy(
        self, from_chat: int, message_id: int, to_chat: int, *, reply_to: int | None = None
    ) -> int | None:
        if message_id in self.gone:
            return None
        self.copies.append((from_chat, message_id, to_chat))
        self.next_id += 1
        return self.next_id

    async def edit(
        self, chat_id: int, message_id: int, text: str, buttons: Keyboard | None = None
    ) -> None:
        self.edits.append(text)

    async def delete(self, chat_id: int, message_id: int) -> None:
        self.deleted.append(message_id)
